# Generated by Django 2.1.7 on 2019-03-31 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Object UUID')),
                ('name', models.CharField(max_length=70, verbose_name='Contact name')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact email address')),
                ('subject', models.CharField(blank=True, max_length=78, verbose_name='Subject of enquiry')),
                ('body', models.CharField(blank=True, max_length=10000, verbose_name='Message text')),
                ('email_error', models.TextField(editable=False, null=True, verbose_name='Email error message')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contact enquiry',
                'verbose_name_plural': 'contact enquiries',
            },
        ),
    ]
