# Generated by Django 2.1.7 on 2019-04-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0002_auto_20190331_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='body',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Message text'),
        ),
    ]
