# Generated by Django 2.1.7 on 2019-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0003_auto_20190413_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=78, null=True)),
                ('send_email', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'contact recipient',
            },
        ),
    ]
