# Generated by Django 2.2.1 on 2019-08-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0004_contactrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrecipient',
            name='send_email',
            field=models.BooleanField(default=True, help_text='Whether or not to send emails to this contact recipient'),
        ),
    ]
