# Generated by Django 2.1.7 on 2019-04-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialinks',
            options={'verbose_name': 'Social media links'},
        ),
    ]
