# Generated by Django 2.1.7 on 2019-04-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links_api', '0002_auto_20190413_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialinks',
            options={'verbose_name': 'social media links'},
        ),
    ]
