# Generated by Django 2.1.7 on 2019-03-25 20:59

from django.db import migrations, models
import image_api.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_width', models.IntegerField(editable=False)),
                ('original_height', models.IntegerField(editable=False)),
                ('original_image', models.ImageField(height_field='original_height', upload_to=image_api.models.upload_to_original_size_folder, width_field='original_width')),
                ('reduced_width', models.IntegerField(editable=False)),
                ('reduced_height', models.IntegerField(editable=False)),
                ('reduced_image', models.ImageField(editable=False, height_field='reduced_height', upload_to=image_api.models.upload_to_reduced_size_folder, width_field='reduced_width')),
                ('title', models.TextField()),
                ('description', models.TextField(null=True)),
                ('media_description', models.TextField(null=True)),
                ('artist_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='tags',
            field=models.ManyToManyField(to='image_api.ItemTag'),
        ),
    ]
