# Generated by Django 2.1.7 on 2019-03-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtag',
            options={'verbose_name': 'Gallery item tag'},
        ),
    ]
