# Generated by Django 2.1.7 on 2019-03-31 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0002_auto_20190331_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ('-created_date', 'title'), 'verbose_name': 'gallery item'},
        ),
        migrations.AlterModelOptions(
            name='itemtag',
            options={'ordering': ('name',), 'verbose_name': 'gallery item tag'},
        ),
    ]
