# Generated by Django 2.1.7 on 2019-03-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0002_auto_20190327_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='media_description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='image_api.ItemTag'),
        ),
    ]
