# Generated by Django 2.2.1 on 2019-05-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0003_auto_20190331_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='size_description',
            field=models.TextField(blank=True),
        ),
    ]
