# Generated by Django 2.2.1 on 2019-05-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0004_galleryitem_size_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='media_description',
            field=models.TextField(blank=True, help_text='e.g. "Oil on Canvas"'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='size_description',
            field=models.TextField(blank=True, help_text='e.g. "8" x 12""'),
        ),
    ]
